version: '3.8'

services:
  mongo-db:
    image: mongo:6.0.6
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      TZ: ${TIME_ZONE}
    volumes:
      - ./mongo:/data/db

  postgres-db:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIME_ZONE}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mysql-db:
    image: mysql:8.0.34
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TIME_ZONE}
    volumes:
      - ./mysql:/var/lib/mysql